ll_deps = [
        "//LinkedList:Linked_List",
]

cc_binary(
    name = "main",
    srcs = ["main.cpp",],
    deps = ll_deps,
)

cc_library(
    name = "Linked_List",
    srcs = ["linkedlist.cpp"], 
    hdrs = ["linkedlist.h"],
    linkstatic = 0,
)